display:
  size:
    x: 100
    y: 25
  unitsize:
    x: 1
    y: 1
  fps: 10

townhall:
  maxhealth: 300
  size:
    x: 8
    y: 5

hut:
  maxhealth: 100
  size:
    x: 2
    y: 2

cannon:
  maxhealth: 100
  size:
    x: 3
    y: 1
  range: 8
  damage: 5

tower:
  maxhealth: 200
  size:
    x: 4
    y: 3
  range: 10
  radius: 1
  damage: 5

wall:
  maxhealth: 30
  size:
    x: 1
    y: 1

king:
  maxhealth: 200
  range: 5
  damage: 25
  speed: 2
  size:
    x: 3
    y: 2

queen:
  maxhealth: 200
  range: 8
  radius: 2
  damage: 15
  speed: 4
  size:
    x: 3
    y: 2

barbarian:
  maxhealth: 50
  damage: 16
  speed: 1
  size:
    x: 1
    y: 2

archer:
  maxhealth: 25
  damage: 8
  speed: 2
  range: 9
  size:
    x: 1
    y: 2

ballon:
  maxhealth: 50
  damage: 32
  speed: 2
  size:
    x: 1
    y: 2

spell:
  rage:
    timecap:
      5
